### ISSUE TITLE
Trouble making nested menus?

### ISSUE THREAD

**Issue by twilightcourier** [heyeshuang/hugo-theme-tokiwa#11]
I am trying to build a website with Hugo. I am having some trouble getting nested menus set up.

I am using your [Tokiwa][1] theme for this project.
[here][2] is a link to my repo.

On the main page of the site I am trying to create menus that slide down to show subfolders, here is an example from the [imperial-library][3] site to show what I mean. You can click on “game books” and then a list opens up that shows all of the available topics for that option. Ex (All, Arena, …) If you click on one of the topics it takes you to a page with a list of all of the entries and a short description of each one. You can then click on the entry to view that post.

In my project my directory is structured

content -> writing (Writing has subfolders poem and stories)

So on the home page I would like for someone to be able to click on “writing” then it would slide down to reveal “poems” and “stories”. You could then click on either one of those to view a list page formatted like

description of poem 1 - link to poem 1

description of poem 2 - link to poem 2

description of poem 3 - link to poem 3

I would also like to add this feature to other topics than only writing.

My config.toml file has the following

``` 
 sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "writing"
    name = "writing"
    url = "/writing"
    weight = 1
     [[menu.main]]
    identifier = "post"
    name = "post"
    url = "/post"
    weight = 2
  [[menu.main]]
    identifier = "poems"
    name = "poems"
    url = "/category/poems"
    parent = "writing"
    weight = 1
  [[menu.main]]
    identifier = "stories"
    name = "stories"
    url = "/category/stories"
    parent = "writing"
    weight = 2
  ```

in my layouts/index.html

```
{{ define "menu-item" }}
  {{ $page := .page }}
  {{ with .entry }}
    {{ if .HasChildren }}
      <li class="{{ if $page.HasMenuCurrent "main" . }}active{{ end }}">
        <a href="{{ .URL }}">{{ .Name }}</a>
        <ul class="sub-menu">
          {{ range .Children }}
            {{ template "menu-item" (dict "entry" . "page" $page) }}
          {{ end }}
        </ul>
      </li>
    {{ else }}
      <li class="{{ if $page.IsMenuCurrent "main" . }}active{{ end }}">
        <a href="{{ .URL }}">{{ .Name }}</a>
      </li>
    {{ end }}
  {{ end }}
{{ end }}

<ul>
  {{ $page := . }}
  {{ range .Site.Menus.main }}
    {{ template "menu-item" (dict "entry" . "page" $page) }}
  {{ end }}
</ul>


```
I also tried following [this example from the hugo docs][4]

Currently my site displays with the theme and when I click on a link the url seems correct ex writing/poems/poem1. 
However, the folders are not displaying correctly.

I have posted this as well on the hugo forums and stackexchange and was unable to quite get my question answered. I browsed through many of the topics on "nesting menus" on the hugo forums and was still unable to exactly figure this out. I would appreciate any assistance you can offer on this. 

Thank you

  [1]: https://github.com/heyeshuang/hugo-theme-tokiwa
  [2]: https://github.com/twilightcourier/blog/tree/dev/courier
  [3]: https://www.imperial-library.info/
  [4]: https://gohugo.io/templates/menu-templates/#menu-entries-from-the-page-s-front-matter

**Comment by heyeshuang** [comment]
Hello Twilightcourier,

For this slide down function you may need to add custom javascript and/or CSS like [this](https://stackoverflow.com/questions/56607716/open-drop-down-menu-onclick-in-sidebar).

**Comment by twilightcourier** [comment]
Thank you for your response, 

Which folder or files would I need to put this custom javascript/CSS into?

**Comment by heyeshuang** [comment]
For example, you can put `custom.css` and `custom.js` into `static/lib/` folder, and add two lines in [baseof.html](https://github.com/heyeshuang/hugo-theme-tokiwa/blob/e826afb4c7fa781de13494b8aa9c2e7c56d6c7b8/layouts/_default/baseof.html#L112):

```html
<link rel="stylesheet" href='{{"lib/custom.css"|absURL}}' crossorigin="anonymous">
<script src='{{"lib/custom.js"|absURL}}' crossorigin="anonymous"></script>
```

Before `</head>` tag.

However, the actual content in `.css/.js` is something you may need to write your own. Wish you good luck and any contribution is welcomed.

**Comment by twilightcourier** [comment]
Thank you for your help!

I have decided to simplify this somewhat for now.

My config.toml is still what I posted earlier.

my content folder is structured

Content -> Writing -> Poems, Short Stories

Poems -> poem1, poem2
Short Stories -> story1, story2

I want to have The main topic (writing) displayed on the home page. If you click on writing I want it to take you to a list page showing the subdirectories “Poems” and “Short Stories” Then if you click on either of those I want it to take you to another list page showing all of the content. I have other broad topics such as “Programming” organized in this same hierarchy and I wanted to get this same set up for each one. Currently my list.html is

```{{ define "main" }}
<main>
<article>
    <header>
        <h1>{{.Title}}</h1>
    </header>
    <!-- "{{.Content}}" pulls from the markdown content of the corresponding _index.md -->
    {{.Content}}
</article>
<ul>
<!-- Ranges through content/posts/*.md -->
{{ range .Pages }}
{{.Dir}}<br>
    <li>
        <a href="{{.Permalink}}">{{.Date.Format "2006-01-02"}} | {{.Title}}</a>
    </li>
{{ end }}
</ul>
{{ end }}
```

Which seems close, but not exactly right.

Thank you for any help you can offer on this issue.

**Comment by heyeshuang** [comment]
I didn't think of that structure before, but it looks like something in https://gohugo.io/content-management/sections/

Or maybe https://gohugo.io/content-management/taxonomies/ would help.

**Comment by twilightcourier** [comment]
Good day,

Trying to implement your previous solution in my static/lib/custom.css I have the following code

```
.flux-overlay{
    position: fixed;
    z-index: 1000;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(255, 155, 61, 3%);
}

.flux-background{

    background: rgba(255, 155, 61, 3%);
}

```

This seems to work locally but on my site I get the following error

```
Access to CSS stylesheet at 'https://twilightcourier.github.io/lib/custom.css' from origin 'https://twilightcourier.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

custom.css:1 Failed to load resource: net::ERR_FAILED
```

Do you have any suggestions on how to resolve this and add my github.io link to the CORS?

Thank you,
Twilight Courier

**Comment by heyeshuang** [comment]
Hi, you may have customed your domain name. Searching `twilightcourier.github.io` in your repo and replace them may help.

**Comment by twilightcourier** [comment]
That seemed to work!

Changing my baseURL in my config.toml got the colors to update on the site.

Thank you so much for developing this theme and your help in getting my website started.

**Comment by heyeshuang** [comment]
Feeling good to hear that :smile:

**Comment by twilightcourier** [comment]
Sorry to reopen this issue,

I noticed that there doesn't seem to be a scrollbar on this site? If I have text that runs longer than 1 page length I seem to be unable to view it. Do you happen to have a suggestion on how to resolve this issue?

*The scroll bars reappear if I delete the custom.css?

**Comment by heyeshuang** [comment]
It seems something in custom.css causes this problem.

**Comment by twilightcourier** [comment]
I figured it out
```
.flux-overlay{
    position: relative;
    z-index: 1000;
    top: 0;
    left: 0;
    min-width: 100%;
    min-height: 100%;
    background: rgba(255, 155, 61, 5%);
}

.flux-background{

    background: rgba(255, 155, 61, 5%);
}

```

Resolved the issue.

Thanks again!
