### ISSUE TITLE
TOC cannot be displayed completely

### ISSUE THREAD

**Issue by sozra** [heyeshuang/hugo-theme-tokiwa#12]
<img width="1052" alt="截屏2021-03-28 上午4 54 09" src="https://user-images.githubusercontent.com/18065661/112734646-04900580-8f82-11eb-900f-26c34863b4b0.png">
There's always a line on the top of TOC that can be only displayed a little bit. I tested using the exampleSite files&config and my own files&config. The problem always exists.

**Comment by heyeshuang** [comment]
I will look for it after work. What kind of browser are you using?

**Comment by sozra** [comment]
I am using Edge. 
I tested the theme in Edge and Chrome before and both had the same problem. But just now I browsed the website in Safari and Firefox and found TOC can be displayed correctly. It seems the problem is related to  Chromium-base browser.

**Comment by sozra** [comment]
I found another similar problem that also happens in Edge and Chrome but not Safari and Firefox. 
<img width="927" alt="截屏2021-03-30 上午12 21 02" src="https://user-images.githubusercontent.com/18065661/112868137-4c33a000-90ee-11eb-9c6f-9128d809cd75.png">
There is a line on the bottom of the post that can't be displayed completely.
If you browser the  official demo site on Edge or Chrome, you might find that problem too.
[tokiwa demo](https://themes.gohugo.io//theme/hugo-theme-tokiwa/post/markdown-syntax/)

**Comment by heyeshuang** [comment]
The latest commit may help. My node environment is broken so I edited the prebuilt CSS file manually :rofl:

**Comment by sozra** [comment]
Thanks, it works perfectly now.

**Comment by heyeshuang** [comment]
👌
