### ISSUE TITLE
image can not be displayed

### ISSUE THREAD

**Issue by houweibo-wm** [heyeshuang/hugo-theme-tokiwa#23]
What is the reason why the image cannot be displayed properly when I insert it locally?
![image](https://user-images.githubusercontent.com/57313187/129480811-c44e2eec-c9f6-4af4-8213-7faa77d2bd78.png)

**Comment by heyeshuang** [comment]
I don't know, maybe this is not a theme issue？

I doubt if the image is at the right place. You may want to double check it.
