### ISSUE TITLE
关于代码优化

### ISSUE THREAD

**Issue by zhu8** [heyeshuang/hugo-theme-tokiwa#24]
@heyeshuang 
你好，很偶然看到你了的主题，非常喜欢，有种日式的性冷淡。

倒腾了一下，发现最后生产出的源代码空格和结构比较混乱，大段空行，看 http://heysh.xyz/hugo-theme-tokiwa/ 也是这样。

但是你的个人站http://blog.heysh.xyz/ ，似乎不是这样的。想了解一下：

1. 如何再不全部更新Theme的源代码的情况下，如果实现？
2. 或者，也可以更新一下Theme源代码，使产出的源代码更Pretty一些？

谢谢！

**Comment by heyeshuang** [comment]
Hello,

我不太明白你的意思，具体是说哪个文件的结构混乱？

**Comment by Zhu8** [comment]
> Hello,
> 
> 我不太明白你的意思，具体是说哪个文件的结构混乱？

不是结构混乱哈，是产生的代码，呃，不优美，各种空行，不对齐，断行之类的。比如上面说的Demo页面的源代码：
`<html>
<body>


  | <!DOCTYPE html>
-- | --
  | <html lang="zh-cn">
  |  
  | <head>
  | <meta charset="utf-8">
  | <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  |  
  | <title>theme 常磐 </title>
  | <meta name="viewport" content="width=device-width,minimum-scale=1">
  | <meta name="generator" content="Hugo 0.70.0" />
  |  
  |  
  | <META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
  |  
  |  
  |  
  |  
  | <link href="/hugo-theme-tokiwa/dist/app.css" rel="stylesheet">
  |  
  |  
  |  
  |  
  |  
  |  
  | <link rel="shortcut icon" href="img/favicon-32x32.png" type="image/png" />
  |  
  |  
  |  
  |  
  | <link rel="alternate" href="/hugo-theme-tokiwa/index.xml" type="application/rss+xml" title="theme 常磐">
  | <link rel="feed" href="/hugo-theme-tokiwa/index.xml" type="application/rss+xml" title="theme 常磐">
  |  
  |  
  |  
  | <script type="application/javascript">
  | var doNotTrack = false;
  | if (!doNotTrack) {
  | window.ga=window.ga\|\|function(){(ga.q=ga.q\|\|[]).push(arguments)};ga.l=+new Date;
  | ga('create', 'UA-FAKE', 'auto');
  |  
  | ga('send', 'pageview');
  | }
  | </script>
  | <script async src='https://www.google-analytics.com/analytics.js'></script>
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <link rel="stylesheet" href='http://heysh.xyz/hugo-theme-tokiwa/lib/katex.min.css' integrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/+DiW/UqRcLbRjq" crossorigin="anonymous">
  |  
  |  
  | <script defer src='http://heysh.xyz/hugo-theme-tokiwa/lib/katex.min.js' integrity="sha384-y23I5Q6l+B6vatafAwxRu/0oK/79VlbSz7Q9aiSZUvyWYIYsd+qj+o24G5ZU2zJz" crossorigin="anonymous"></script>
  |  
  |  
  | <script defer src='http://heysh.xyz/hugo-theme-tokiwa/lib/contrib/auto-render.min.js' integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI"
  | crossorigin="anonymous"
  | onload='renderMathInElement(document.body);'></script>
  |  
  |  
  | <script>
  | document.addEventListener("DOMContentLoaded", function() {
  | renderMathInElement(document.body, {
  | delimiters: [
  | {left: "$", right: "$", display: true},
  | {left: "$", right: "$", display: false}
  | ]
  | });
  | });
  | </script>
  |  
  |  
  |  
  |  
  | <script>
  | (function (u, c) {
  | var d = document,
  | t = 'script',
  | o = d.createElement(t),
  | s = d.getElementsByTagName(t)[0];
  | o.src = u;
  | if (c) {
  | o.addEventListener('load', function (e) {
  | c(e);
  | });
  | }
  | s.parentNode.insertBefore(o, s);
  | })('http:\/\/heysh.xyz\/hugo-theme-tokiwa\/lib\/pangu.min.js', function () {
  | pangu.spacingPage();
  | });
  | </script>
  |  
  |  
  | <style type="text/css" media="screen, print">
  | @font-face {
  | font-family: "FancyTitleFont";
  | font-style: normal;
  | font-display: swap;
  | src: url('http://heysh.xyz/hugo-theme-tokiwa/fonts/exampleFont.woff2') format('woff2'),
  | url('http://heysh.xyz/hugo-theme-tokiwa/fonts/exampleFont.woff') format('woff');
  | }
  |  
  |  
  | @font-face {
  | font-family: 'Noto Serif CJK SC';
  | font-style: normal;
  | font-weight: 300;
  | font-display: swap;
  | src: local('Noto Serif CJK SC Light'), local('NotoSerifCJK-Light'),
  | url('http://heysh.xyz/hugo-theme-tokiwa/fonts/noto-serif-sc-v7-latin_chinese-simplified-300.woff2') format('woff2'),
  |  
  | url('http://heysh.xyz/hugo-theme-tokiwa/fonts/noto-serif-sc-v7-latin_chinese-simplified-300.woff') format('woff');
  |  
  | }
  |  
  |  
  | @font-face {
  | font-family: 'Noto Serif CJK SC';
  | font-style: normal;
  | font-weight: 400;
  | font-display: swap;
  | src: local('Noto Serif CJK SC'), local('NotoSerifCJK-Regular'),
  | url('http://heysh.xyz/hugo-theme-tokiwa/fonts/noto-serif-sc-v7-latin_chinese-simplified-regular.woff2') format('woff2'),
  |  
  | url('http://heysh.xyz/hugo-theme-tokiwa/fonts/noto-serif-sc-v7-latin_chinese-simplified-regular.woff') format('woff');
  |  
  | }
  |  
  |  
  | @font-face {
  | font-family: 'Noto Serif CJK SC';
  | font-style: normal;
  | font-weight: 500;
  | font-display: swap;
  | src: local('Noto Serif CJK SC Medium'), local('NotoSerifCJK-Medium'),
  | url('http://heysh.xyz/hugo-theme-tokiwa/fonts/noto-serif-sc-v7-latin_chinese-simplified-500.woff2') format('woff2'),
  |  
  | url('http://heysh.xyz/hugo-theme-tokiwa/fonts/noto-serif-sc-v7-latin_chinese-simplified-500.woff') format('woff');
  |  
  | }
  | </style>
  |  
  |  
  | </head>
  |  
  | <body class="bg-gray-100 text-gray-700 font-sans">
  | <div class="p-6 sm:p-10 md:p-16 flex flex-wrap">
  | <header class="w-full md:w-2/5 xl:w-1/2 md:pr-12 lg:pr-20 xl:pr-24 order-1 md:order-1 max-w-2xl">
  | <div
  | class="z-50 bg-gray-100 lg:min-w-0.7 max-w-xl md:float-right md:text-right leading-loose tracking-tight md:sticky md:top-0 pt-2">
  | <div class="pb-4">
  | <h1 >
  | <a href="http://heysh.xyz/hugo-theme-tokiwa/" title="theme 常磐" class="heading font-cursive icon">theme 常磐</a>
  | </h1>
  | </div>
  | <ul class="font-serif flex-grow-0 flex justify-between flex-wrap md:flex-col">
  |  
  |  
  | <li class="px-1 md:px-0">
  | <a href="/hugo-theme-tokiwa/post/" title="归档 page" >
  | 归档
  | </a>
  | </li>
  |  
  | <li class="px-1 md:px-0">
  | <a href="/hugo-theme-tokiwa/categories/" title="Categories page" >
  | Categories
  | </a>
  | </li>
  |  
  | <li class="px-1 md:px-0">
  | <a href="/hugo-theme-tokiwa/tags/" title="Tags page" >
  | Tags
  | </a>
  | </li>
  |  
  | <li class="px-1 md:px-0">
  | <a href="/hugo-theme-tokiwa/about/" title="About page" >
  | About
  | </a>
  | </li>
  |  
  | <li class="px-1 md:px-0">
  | <a href="/hugo-theme-tokiwa/wallet/" title="Begging page" >
  | Begging
  | </a>
  | </li>
  |  
  | <li class="px-1 md:px-0">
  | <a href="https://heysh.xyz/" title="Bud page" >
  | Bud
  | </a>
  | </li>
  |  
  | <li class="px-1 md:px-0">
  | <a href="/hugo-theme-tokiwa/sentences/" title="Theatre page" >
  | Theatre
  | </a>
  | </li>
  |  
  |  
  | <li>
  | <a href='/hugo-theme-tokiwa/index.xml'>RSS</a>
  | </li>
  |  
  |  
  | </ul>
  | </div>
  | </header>
  | <main role="main" class="w-full md:w-3/5 xl:w-1/2 max-w-3xl order-2 md:order-2 min-h-70vh pt-2 pb-4">
  |  
  |  
  | <div class="font-serif text-medium-red-violet-400 pt-3">
  | Tokiwa-iro is the theme color of this site.
  | </div>
  | <hr  class="pt-2"/>
  |  
  |  
  | <div>
  | <section>
  |  
  | <div>
  | <div class="pb-8">
  | <div class="font-serif font-medium text-xl">
  | <a href="http://heysh.xyz/hugo-theme-tokiwa/post/markdown-syntax/">
  | Markdown Syntax Guide
  | </a>
  | </div>
  |  
  |  
  |  
  |  
  | <div class="font-serif text-gray-600 font-light pt-1">
  | Sample article showcasing basic Markdown syntax and formatting for HTML elements.</div>
  |  
  |  
  | <div class="flex flex-wrap justify-between pt-1"><div class="md:flex-grow-0 font-light">
  |  
  |  
  |  
  |  
  | <a class="post-taxonomy-category text-medium-red-violet-600 hover:text-medium-red-violet-400"
  | href='/hugo-theme-tokiwa/categories/themes'>themes</a>&nbsp;&#47;
  |  
  | <a class="post-taxonomy-category text-medium-red-violet-600 hover:text-medium-red-violet-400"
  | href='/hugo-theme-tokiwa/categories/syntax'>syntax</a>
  |  
  |  
  |  
  |  
  |  
  | &nbsp;&nbsp;
  |  
  |  
  |  
  |  
  |  
  |  
  | <a class="post-taxonomy-tag text-eucalyptus-500"
  | href='/hugo-theme-tokiwa/tags/markdown'>markdown</a>&nbsp;&#47;
  |  
  | <a class="post-taxonomy-tag text-eucalyptus-500"
  | href='/hugo-theme-tokiwa/tags/css'>css</a>&nbsp;&#47;
  |  
  | <a class="post-taxonomy-tag text-eucalyptus-500"
  | href='/hugo-theme-tokiwa/tags/html'>html</a>&nbsp;&#47;
  |  
  | <a class="post-taxonomy-tag text-eucalyptus-500"
  | href='/hugo-theme-tokiwa/tags/themes'>themes</a>
  |  
  |  
  |  
  | </div><time class="text-eucalyptus-500 md:text-right md:flex-grow font-light"
  | datetime="2019-03-11T00:00:00Z">2019-3-11 00:00</time>
  | </div>
  | </div>
  | </div>
  | <div>
  | <div class="pb-8">
  | <div class="font-serif font-medium text-xl">
  | <a href="http://heysh.xyz/hugo-theme-tokiwa/post/placeholder-text/">
  | Placeholder Text
  | </a>
  | </div>
  |  
  |  
  |  
  |  
  | <div class="font-serif text-gray-600 font-light pt-1">
  | Lorem Ipsum Dolor Si Amet</div>
  |  
  |  
  | <div class="flex flex-wrap justify-between pt-1"><div class="md:flex-grow-0 font-light">
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <a class="post-taxonomy-tag text-eucalyptus-500"
  | href='/hugo-theme-tokiwa/tags/markdown'>markdown</a>&nbsp;&#47;
  |  
  | <a class="post-taxonomy-tag text-eucalyptus-500"
  | href='/hugo-theme-tokiwa/tags/text'>text</a>
  |  
  |  
  |  
  | </div><time class="text-eucalyptus-500 md:text-right md:flex-grow font-light"
  | datetime="2019-03-09T00:00:00Z">2019-3-9 00:00</time>
  | </div>
  | </div>
  | </div>
  | <div>
  | <div class="pb-8">
  | <div class="font-serif font-medium text-xl">
  | <a href="http://heysh.xyz/hugo-theme-tokiwa/post/math-typesetting/">
  | Math Typesetting
  | </a>
  | </div>
  |  
  |  
  |  
  |  
  | <div class="font-serif text-gray-600 font-light pt-1">
  | A brief guide to setup KaTeX</div>
  |  
  |  
  | <div class="flex flex-wrap justify-between pt-1"><div class="md:flex-grow-0 font-light">
  |  
  |  
  |  
  |  
  |  
  | </div><time class="text-eucalyptus-500 md:text-right md:flex-grow font-light"
  | datetime="2019-03-08T00:00:00Z">2019-3-8 00:00</time>
  | </div>
  | </div>
  | </div>
  | <div>
  | <div class="pb-8">
  | <div class="font-serif font-medium text-xl">
  | <a href="http://heysh.xyz/hugo-theme-tokiwa/post/emoji-support/">
  | Emoji Support
  | </a>
  | </div>
  |  
  |  
  |  
  |  
  | <div class="font-serif text-gray-600 font-light pt-1">
  | Guide to emoji usage in Hugo</div>
  |  
  |  
  | <div class="flex flex-wrap justify-between pt-1"><div class="md:flex-grow-0 font-light">
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <a class="post-taxonomy-tag text-eucalyptus-500"
  | href='/hugo-theme-tokiwa/tags/emoji'>emoji</a>
  |  
  |  
  |  
  | </div><time class="text-eucalyptus-500 md:text-right md:flex-grow font-light"
  | datetime="2019-03-05T00:00:00Z">2019-3-5 00:00</time>
  | </div>
  | </div>
  | </div>
  |  
  | </section>
  | </div>
  |  
  | </main>
  | <aside role="contentinfo"
  | class="w-full md:w-2/5 xl:w-1/2 md:pr-12 lg:pr-20 xl:pr-24 order-4 md:order-3 md:sticky md:bottom-0 self-end max-w-2xl">
  | <div class="md:float-right md:text-right leading-loose tracking-tight md:mb-2">
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <div class="md:max-w-xs  flex flex-col md:items-end pt-2">
  |  
  |  
  | <div class="flex flex-wrap-reverse md:justify-end content-end md:content-start justify-start items-start md:flex-col pb-2 max-h-16">
  |  
  | <a href="https://twitter.com/hh" target="_blank" class="bilibili icon pl-1 text-eucalyptus-400 hover:text-java-400" title="bilibili link" rel="noopener" aria-label="follow on bilibili——Opens in a new window">
  |  
  | <div class="fill-current h-8 w-8">
  | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  | <g>
  | <path fill="none" d="M0 0h24v24H0z"/>
  | <path d="M7.172 2.757L10.414 6h3.171l3.243-3.242a1 1 0 0 1 1.415 1.415l-1.829 1.827L18.5 6A3.5 3.5 0 0 1 22 9.5v8a3.5 3.5 0 0 1-3.5 3.5h-13A3.5 3.5 0 0 1 2 17.5v-8A3.5 3.5 0 0 1 5.5 6h2.085L5.757 4.171a1 1 0 0 1 1.415-1.415zM18.5 8h-13a1.5 1.5 0 0 0-1.493 1.356L4 9.5v8a1.5 1.5 0 0 0 1.356 1.493L5.5 19h13a1.5 1.5 0 0 0 1.493-1.356L20 17.5v-8A1.5 1.5 0 0 0 18.5 8zM8 11a1 1 0 0 1 1 1v2a1 1 0 0 1-2 0v-2a1 1 0 0 1 1-1zm8 0a1 1 0 0 1 1 1v2a1 1 0 0 1-2 0v-2a1 1 0 0 1 1-1z"/>
  | </g>
  | </svg>
  |  
  | </div>
  | </a>
  |  
  | <a href="https://github.com/hh" target="_blank" class="github icon pl-1 text-eucalyptus-400 hover:text-java-400" title="github link" rel="noopener" aria-label="follow on github——Opens in a new window">
  |  
  | <div class="fill-current h-8 w-8">
  | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  | <g>
  | <path fill="none" d="M0 0h24v24H0z"/>
  | <path fill-rule="nonzero" d="M5.883 18.653c-.3-.2-.558-.455-.86-.816a50.32 50.32 0 0 1-.466-.579c-.463-.575-.755-.84-1.057-.949a1 1 0 0 1 .676-1.883c.752.27 1.261.735 1.947 1.588-.094-.117.34.427.433.539.19.227.33.365.44.438.204.137.587.196 1.15.14.023-.382.094-.753.202-1.095C5.38 15.31 3.7 13.396 3.7 9.64c0-1.24.37-2.356 1.058-3.292-.218-.894-.185-1.975.302-3.192a1 1 0 0 1 .63-.582c.081-.024.127-.035.208-.047.803-.123 1.937.17 3.415 1.096A11.731 11.731 0 0 1 12 3.315c.912 0 1.818.104 2.684.308 1.477-.933 2.613-1.226 3.422-1.096.085.013.157.03.218.05a1 1 0 0 1 .616.58c.487 1.216.52 2.297.302 3.19.691.936 1.058 2.045 1.058 3.293 0 3.757-1.674 5.665-4.642 6.392.125.415.19.879.19 1.38a300.492 300.492 0 0 1-.012 2.716 1 1 0 0 1-.019 1.958c-1.139.228-1.983-.532-1.983-1.525l.002-.446.005-.705c.005-.708.007-1.338.007-1.998 0-.697-.183-1.152-.425-1.36-.661-.57-.326-1.655.54-1.752 2.967-.333 4.337-1.482 4.337-4.66 0-.955-.312-1.744-.913-2.404a1 1 0 0 1-.19-1.045c.166-.414.237-.957.096-1.614l-.01.003c-.491.139-1.11.44-1.858.949a1 1 0 0 1-.833.135A9.626 9.626 0 0 0 12 5.315c-.89 0-1.772.119-2.592.35a1 1 0 0 1-.83-.134c-.752-.507-1.374-.807-1.868-.947-.144.653-.073 1.194.092 1.607a1 1 0 0 1-.189 1.045C6.016 7.89 5.7 8.694 5.7 9.64c0 3.172 1.371 4.328 4.322 4.66.865.097 1.201 1.177.544 1.748-.192.168-.429.732-.429 1.364v3.15c0 .986-.835 1.725-1.96 1.528a1 1 0 0 1-.04-1.962v-.99c-.91.061-1.662-.088-2.254-.485z"/>
  | </g>
  | </svg>
  |  
  | </div>
  | </a>
  |  
  | <a href="https://twitter.com/hh" target="_blank" class="gitlab icon pl-1 text-eucalyptus-400 hover:text-java-400" title="gitlab link" rel="noopener" aria-label="follow on gitlab——Opens in a new window">
  |  
  | <div class="fill-current h-8 w-8">
  | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  | <g>
  | <path fill="none" d="M0 0h24v24H0z"/>
  | <path fill-rule="nonzero" d="M5.68 7.314l-1.82 5.914L12 19.442l8.14-6.214-1.82-5.914L16.643 11H7.356L5.681 7.314zM15.357 9l2.888-6.354a.4.4 0 0 1 .747.048l3.367 10.945a.5.5 0 0 1-.174.544L12 21.958 1.816 14.183a.5.5 0 0 1-.174-.544L5.009 2.694a.4.4 0 0 1 .747-.048L8.644 9h6.712z"/>
  | </g>
  | </svg>
  |  
  | </div>
  | </a>
  |  
  | <a href="https://twitter.com/hh" target="_blank" class="instagram icon pl-1 text-eucalyptus-400 hover:text-java-400" title="instagram link" rel="noopener" aria-label="follow on instagram——Opens in a new window">
  |  
  | <div class="fill-current h-8 w-8">
  | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  | <g>
  | <path fill="none" d="M0 0h24v24H0z"/>
  | <path fill-rule="nonzero" d="M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm0-2a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm6.5-.25a1.25 1.25 0 0 1-2.5 0 1.25 1.25 0 0 1 2.5 0zM12 4c-2.474 0-2.878.007-4.029.058-.784.037-1.31.142-1.798.332-.434.168-.747.369-1.08.703a2.89 2.89 0 0 0-.704 1.08c-.19.49-.295 1.015-.331 1.798C4.006 9.075 4 9.461 4 12c0 2.474.007 2.878.058 4.029.037.783.142 1.31.331 1.797.17.435.37.748.702 1.08.337.336.65.537 1.08.703.494.191 1.02.297 1.8.333C9.075 19.994 9.461 20 12 20c2.474 0 2.878-.007 4.029-.058.782-.037 1.309-.142 1.797-.331.433-.169.748-.37 1.08-.702.337-.337.538-.65.704-1.08.19-.493.296-1.02.332-1.8.052-1.104.058-1.49.058-4.029 0-2.474-.007-2.878-.058-4.029-.037-.782-.142-1.31-.332-1.798a2.911 2.911 0 0 0-.703-1.08 2.884 2.884 0 0 0-1.08-.704c-.49-.19-1.016-.295-1.798-.331C14.925 4.006 14.539 4 12 4zm0-2c2.717 0 3.056.01 4.122.06 1.065.05 1.79.217 2.428.465.66.254 1.216.598 1.772 1.153a4.908 4.908 0 0 1 1.153 1.772c.247.637.415 1.363.465 2.428.047 1.066.06 1.405.06 4.122 0 2.717-.01 3.056-.06 4.122-.05 1.065-.218 1.79-.465 2.428a4.883 4.883 0 0 1-1.153 1.772 4.915 4.915 0 0 1-1.772 1.153c-.637.247-1.363.415-2.428.465-1.066.047-1.405.06-4.122.06-2.717 0-3.056-.01-4.122-.06-1.065-.05-1.79-.218-2.428-.465a4.89 4.89 0 0 1-1.772-1.153 4.904 4.904 0 0 1-1.153-1.772c-.248-.637-.415-1.363-.465-2.428C2.013 15.056 2 14.717 2 12c0-2.717.01-3.056.06-4.122.05-1.066.217-1.79.465-2.428a4.88 4.88 0 0 1 1.153-1.772A4.897 4.897 0 0 1 5.45 2.525c.638-.248 1.362-.415 2.428-.465C8.944 2.013 9.283 2 12 2z"/>
  | </g>
  | </svg>
  |  
  | </div>
  | </a>
  |  
  | <a href="https://twitter.com/heyeshuang" target="_blank" class="twitter icon pl-1 text-eucalyptus-400 hover:text-java-400" title="twitter link" rel="noopener" aria-label="follow on twitter——Opens in a new window">
  |  
  | <div class="fill-current h-8 w-8">
  | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  | <g>
  | <path fill="none" d="M0 0h24v24H0z"/>
  | <path fill-rule="nonzero" d="M15.3 5.55a2.9 2.9 0 0 0-2.9 2.847l-.028 1.575a.6.6 0 0 1-.68.583l-1.561-.212c-2.054-.28-4.022-1.226-5.91-2.799-.598 3.31.57 5.603 3.383 7.372l1.747 1.098a.6.6 0 0 1 .034.993L7.793 18.17c.947.059 1.846.017 2.592-.131 4.718-.942 7.855-4.492 7.855-10.348 0-.478-1.012-2.141-2.94-2.141zm-4.9 2.81a4.9 4.9 0 0 1 8.385-3.355c.711-.005 1.316.175 2.669-.645-.335 1.64-.5 2.352-1.214 3.331 0 7.642-4.697 11.358-9.463 12.309-3.268.652-8.02-.419-9.382-1.841.694-.054 3.514-.357 5.144-1.55C5.16 15.7-.329 12.47 3.278 3.786c1.693 1.977 3.41 3.323 5.15 4.037 1.158.475 1.442.465 1.973.538z"/>
  | </g>
  | </svg>
  |  
  | </div>
  | </a>
  |  
  | <a href="https://twitter.com/hh" target="_blank" class="weibo icon pl-1 text-eucalyptus-400 hover:text-java-400" title="weibo link" rel="noopener" aria-label="follow on weibo——Opens in a new window">
  |  
  | <div class="fill-current h-8 w-8">
  | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  | <g>
  | <path fill="none" d="M0 0h24v24H0z"/>
  | <path fill-rule="nonzero" d="M20.194 14.197c0 3.362-4.53 6.424-9.926 6.424C5.318 20.62 1 18.189 1 14.534c0-1.947 1.18-4.087 3.24-6.088 2.832-2.746 6.229-4.033 7.858-2.448.498.482.723 1.122.719 1.858 1.975-.576 3.65-.404 4.483.752.449.623.532 1.38.326 2.207 1.511.61 2.568 1.77 2.568 3.382zm-4.44-2.07c-.386-.41-.4-.92-.198-1.41.208-.508.213-.812.12-.94-.264-.368-1.533-.363-3.194.311a2.043 2.043 0 0 1-.509.14c-.344.046-.671.001-.983-.265-.419-.359-.474-.855-.322-1.316.215-.67.18-1.076.037-1.215-.186-.18-.777-.191-1.659.143-1.069.405-2.298 1.224-3.414 2.306C3.925 11.54 3 13.218 3 14.534c0 2.242 3.276 4.087 7.268 4.087 4.42 0 7.926-2.37 7.926-4.424 0-.738-.637-1.339-1.673-1.652-.394-.113-.536-.171-.767-.417zm7.054-1.617a1 1 0 0 1-1.936-.502 4 4 0 0 0-4.693-4.924 1 1 0 1 1-.407-1.958 6 6 0 0 1 7.036 7.384z"/>
  | </g>
  | </svg>
  |  
  | </div>
  | </a>
  |  
  | <a href="https://twitter.com/hh" target="_blank" class="youtube icon pl-1 text-eucalyptus-400 hover:text-java-400" title="youtube link" rel="noopener" aria-label="follow on youtube——Opens in a new window">
  |  
  | <div class="fill-current h-8 w-8">
  | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  | <g>
  | <path fill="none" d="M0 0h24v24H0z"/>
  | <path fill-rule="nonzero" d="M19.606 6.995c-.076-.298-.292-.523-.539-.592C18.63 6.28 16.5 6 12 6s-6.628.28-7.069.403c-.244.068-.46.293-.537.592C4.285 7.419 4 9.196 4 12s.285 4.58.394 5.006c.076.297.292.522.538.59C5.372 17.72 7.5 18 12 18s6.629-.28 7.069-.403c.244-.068.46-.293.537-.592C19.715 16.581 20 14.8 20 12s-.285-4.58-.394-5.005zm1.937-.497C22 8.28 22 12 22 12s0 3.72-.457 5.502c-.254.985-.997 1.76-1.938 2.022C17.896 20 12 20 12 20s-5.893 0-7.605-.476c-.945-.266-1.687-1.04-1.938-2.022C2 15.72 2 12 2 12s0-3.72.457-5.502c.254-.985.997-1.76 1.938-2.022C6.107 4 12 4 12 4s5.896 0 7.605.476c.945.266 1.687 1.04 1.938 2.022zM10 15.5v-7l6 3.5-6 3.5z"/>
  | </g>
  | </svg>
  |  
  | </div>
  | </a>
  |  
  | <a href="https://twitter.com/hh" target="_blank" class="zhihu icon pl-1 text-eucalyptus-400 hover:text-java-400" title="zhihu link" rel="noopener" aria-label="follow on zhihu——Opens in a new window">
  |  
  | <div class="fill-current h-8 w-8">
  | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  | <g>
  | <path fill="none" d="M0 0h24v24H0z"/>
  | <path d="M12.344 17.963l-1.688 1.074-2.131-3.35c-.44 1.402-1.172 2.665-2.139 3.825-.402.483-.82.918-1.301 1.375-.155.147-.775.717-.878.82l-1.414-1.414c.139-.139.787-.735.915-.856.43-.408.795-.79 1.142-1.206 1.266-1.518 2.03-3.21 2.137-5.231H3v-2h4V7h-.868c-.689 1.266-1.558 2.222-2.618 2.857L2.486 8.143c1.395-.838 2.425-2.604 3.038-5.36l1.952.434c-.14.633-.303 1.227-.489 1.783H11.5v2H9v4h2.5v2H9.185l3.159 4.963zm3.838-.07L17.298 17H19V7h-4v10h.736l.446.893zM13 5h8v14h-3l-2.5 2-1-2H13V5z"/>
  | </g>
  | </svg>
  |  
  | </div>
  | </a>
  |  
  | </div>
  | <div class="a-gray text-sm text-gray-500 leading-tight">
  | Copyright © 2008–2019
  | <br />
  | Built with Hugo and theme <a
  | href="https://github.com/heyeshuang/hugo-theme-tokiwa">Tokiwa</a>.
  | <br />
  | 21 pages, 1147 words in total.
  | </div>
  | </div>
  | </div>
  | </aside>
  | <footer class="w-full md:w-3/5 xl:w-1/2 order-3 max-w-3xl md:order-4 pt-2">
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | </footer>
  |  
  |  
  | <script src="/hugo-theme-tokiwa/dist/app.js"></script>
  |  
  | </div>
  | </body>
  |  
  | </html>


</body>
</html>`

**Comment by zhu8** [comment]
> Hello,
> 
> 我不太明白你的意思，具体是说哪个文件的结构混乱？

简单来说，就是页面生产出来，带有大量的空白行。而你个人网站：http://blog.heysh.xyz/ 的源代码，却是非常干净和紧密的，完全没有空白行，也没有缩进。这样生成的HTML源代码即不至于无法阅读，又有最小的体积，
所以我其实就是想了解一下，这个是怎么实现的。

谢谢你！

**Comment by heyeshuang** [comment]
Hi @Zhu8 

这个我不大清楚，但是看起来好像是Hugo本身的一个特性，刚才搜索的时候发现了两个链接：

https://discourse.gohugo.io/t/how-do-i-avoid-the-blank-lines-in-the-generated-html/3157
https://discourse.gohugo.io/t/blank-lines-in-generated-html-code/4013

大意是说源文件里的注释会产生空行。至于为什么我自己的博客里没有出现这个，我暂且蒙在鼓里。

**Comment by zhu8** [comment]
> Hi @Zhu8
> 
> 这个我不大清楚，但是看起来好像是Hugo本身的一个特性，刚才搜索的时候发现了两个链接：
> 
> https://discourse.gohugo.io/t/how-do-i-avoid-the-blank-lines-in-the-generated-html/3157 https://discourse.gohugo.io/t/blank-lines-in-generated-html-code/4013
> 
> 大意是说源文件里的注释会产生空行。至于为什么我自己的博客里没有出现这个，我暂且蒙在鼓里。

哈哈，好的，大致明白了。我以为你是有什么神秘方法的，特别请教一下的，感谢！
