### ISSUE TITLE
About Google Analytics issue

### ISSUE THREAD

**Issue by bored2020** [heyeshuang/hugo-theme-tokiwa#41]
When i want to use Google Analytics in my website from your template.I find that in the config.toml must capitalize "G" in config.toml - "GoogleAnalyticsID" - for it to work. 

Thanks for your selfless sharing your beautiful work.

**Comment by heyeshuang** [comment]
This theme uses Hugo’s [Internal Templates for GA](https://gohugo.io/templates/internal/#configure-google-analytics), and it calls like:

```toml
googleAnalytics = 'G-MEASUREMENT_ID'
```

So I donno...

**Comment by bored2020** [comment]
Maybe its the hugo's bug.

**Comment by heyeshuang** [comment]
Google analytics works well for my personal blog, sorry for not able to help
