### ISSUE TITLE
I’m having an issue with rendering on my Hugo site using the Tokiwa theme.

### ISSUE THREAD

**Issue by chirag-urb** [heyeshuang/hugo-theme-tokiwa#45]
it’s looks like it’ s
same problem with ''  and  ""
It leaves huge space. 
This problem is consistent throughout my entire site. Does anyone know how to fix this?
Also how do I change numbering system from greek to normal one?
![image](https://github.com/user-attachments/assets/b60160cb-af57-4512-ab65-3a0b35f1cdff)

Any help or suggestions would be greatly appreciated. Thanks in advance!

**Comment by heyeshuang** [comment]
Hi, sorry for late response.

First issue is about `pangu.js` at [here](https://github.com/heyeshuang/hugo-theme-tokiwa/blob/dd607ca18911aafed5f551e1cf02561fd4ba26f5/layouts/_default/baseof.html#L41). It is used for add spaces between Chinese characters and numbers etc. 

For second issue, you can search `lower-greek` at [app.css](https://github.com/heyeshuang/hugo-theme-tokiwa/blob/master/static/dist/app.css) and change it to, `decimal`, maybe.

I'm afraid I can't change them for you, for I have already lost my knowledge about HTML.

By the way, your homepage looks nice :wink:

**Comment by chirag-urb** [comment]
Hey, thanks for the reply, I ended up creating a theme from scratch inspired by yours and X-min.
