### ISSUE TITLE
Suggestion: svg image file for email

### ISSUE THREAD

**Issue by miwie** [heyeshuang/hugo-theme-tokiwa#5]
I'd like to see a svg image file in layouts/partials/svg/ for email. 
Or is there any suggestion which of the existing svg fils could be used for this?

**Comment by heyeshuang** [comment]
Okay, forgot it and just added! Use it like `mail="mailto:anon@example.com"`

By the way, in case you want some other icons, just copy them from <https://github.com/Remix-Design/RemixIcon/tree/master/icons> to `layouts/partials/svg/`, and send me a pull request (or issue) :smile:

**Comment by miwie** [comment]
Xiè xie!

**Comment by heyeshuang** [comment]
Bitte :wink:
