### ISSUE TITLE
不太清楚怎么支持KaTeX

### ISSUE THREAD

**Issue by Luosuu** [heyeshuang/hugo-theme-tokiwa#8]
作者您好，我不太熟悉Hugo的配置，您在
https://themes.gohugo.io//theme/hugo-theme-tokiwa/post/math-typesetting/
里面说“Include the partial in your templates like so:”
{{ if or .Params.math .Site.Params.math }}
{{ partial "math.html" . }}
{{ end }}
我应该在哪里写这段代码呢
是我新创建的/layouts/partials/math.html吗？
我把 https://katex.org/docs/autorender.html 里的第一个代码块复制进了math.html，然后又将上面那一段复制进了math.html，网站没有build成功。
另外，我想确认一下这个/layouts文件夹应该是我的站点目录底下的，而非themes/hugo-theme-tokiwa/layouts吧。
感谢作者！！
如果能把 https://themes.gohugo.io//theme/hugo-theme-tokiwa 这个网站的文件配置告诉我就最好了！

**Comment by heyeshuang** [comment]
Hello，你引用的[这个网址](https://themes.gohugo.io//theme/hugo-theme-tokiwa/post/math-typesetting/)只是Hugo的测试站点，通过[这里](https://github.com/heyeshuang/hugo-theme-tokiwa/blob/master/exampleSite/)的源文件生成，每个都是一样的，里面的内容不能算数😂

具体到你的问题，不需要改原代码，只要在`config.toml`里面`[params]`部分加上`math=true`就行，像<https://github.com/heyeshuang/hugo-theme-tokiwa/blob/master/exampleSite/config.toml>一样

**Comment by Luosuu** [comment]
> Hello，你引用的[这个网址](https://themes.gohugo.io//theme/hugo-theme-tokiwa/post/math-typesetting/)只是Hugo的测试站点，通过[这里](https://github.com/heyeshuang/hugo-theme-tokiwa/blob/master/exampleSite/)的源文件生成，每个都是一样的，里面的内容不能算数😂
> 
> 具体到你的问题，不需要改原代码，只要在`config.toml`里面`[params]`部分加上`math=true`就行，像https://github.com/heyeshuang/hugo-theme-tokiwa/blob/master/exampleSite/config.toml一样

感谢！可是我已经在config.toml中的[params]中加入了math=true，我是不是必须在每篇文章的frontmatter加上 marup:mmark才行呢？我自己测试的时候如果不加markup:mmark，数学公式还是不能渲染成功。

**Comment by heyeshuang** [comment]
我这里没有遇见这个问题，在普通的md文件下也可以渲染。我这里的公式是用`$`或`$$`包裹的。

另外，把Hugo升级到较新版本也许有帮助，我用的是0.73.0.

**Comment by Luosuu** [comment]
感谢提醒！我的hugo版本也是0.73.0，数学公式也是使用$和$$包裹...检查了[params]里确实是写好了math=true的。但确实不能渲染成功（frontmatter不加markup:mmark的情况下），，我实在想不出可能哪里出了问题，请问作者大大有什么建议吗。
我注意到行内数学公式是可以渲染成功的（用$包裹），但是数学公式块就不行（用$$包裹的）

**Comment by heyeshuang** [comment]
这个有点神奇…可以添加/删除$$前后的空格试试？

**Comment by Luosuu** [comment]
感谢作者！我发现是在数学公式中使用了` *` 这个符号导致的，我把`*`符号都换成`\cdot`后就没问题了！可能是`*`这个符号匹配的时候渲染出了问题(我也不太懂）。
